config/routes.rb
SendEmail::Application.routes.draw do
  root :to => 'welcome#index'
  get 'welcome/say_hello' => 'welcome#say'

  get 'welcome' => 'welcome#index'

  get 'welcome/index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :capacity, :description, :is_public, :name
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/client_controller.rb
class ClientController < ActionController::Base
require 'mail'

 #  def send_email
	# sendgrid = SendGrid::Client.new do |c|
	# c.api_key = 'SENDGRID_APIKEY'
	# Mail.defaults do
	#  delivery_method :smtp, { :address   => "smtp.gmail.com",
	#                            :port      => 587,
	#                            :domain    => "gmail.com",
	#                            :user_name => "wangekko@gmail.com",
	#                            :password  => "whang.92",
	#                            :authentication => 'plain',
	#                            :enable_starttls_auto => true }
	# end

	# email = Mail.deliver do
	#   to 'liang.wang@laxino.com'
	#   from 'wangekko@gmail.com'
	#   subject 'This is the subject of your email'
	#   text_part do
	#     body 'Hello world in text'
	#   end
	#   html_part do
	#     content_type 'text/html; charset=UTF-8'
	#     body '<b>Hello world in HTML</b>'
	#   end
	# end	
	# res = sendgrid.send(email)
	# puts res.code
 #  puts res.body
 #  end
 def send_email
      Mail.defaults do
        delivery_method :smtp, { :address => 'moexc01.mo.laxino.com', :openssl_verify_mode => OpenSSL::SSL::VERIFY_NONE,:enable_starttls_auto => true}
      end
      mail = Mail.new
      mail.from = 'noreply@laxino.com'
      mail.to = 'liang.wang@laxino.com'
      mail.subject = 'This is the subject of your email'
      mail.body =  'Date:   Sun, 12 Oct 2014 13:42:23
										Action:  alert
										Event:  Connection succeeded
										Host:   snd-cons-app01.sbox.mb.idc02.laxigames.local
										Service: sgsms_erk_wutai
										Description: connection succeeded to INET[snd-cons-app01.sbox.mb.idc02.laxigames.local:9086] via TCP
										Please refer to Monit Service Manager for more details:   http://snd-cons-app01.sbox.mb.idc02.laxigames.local:2812/
										Yours sincerely,
										Monit@Core System Development, R & D'
      mail.deliver!  	
 end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_even, :only => [:show, :edit, :update, :destoy]

  def set_evet
    @event = Event.find(event_id)
  end

  def index
    @events = Event.all
  end

  def new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = 'event was successfully created'  
      redirect_to :action => :index
    else
      falsh[:alert] = 'Event create fail'
      render :action => :new
    end
  end
    
  def destoy
    @event.distory
    redirect_to :action => :index
  end

  def update
    if @event.update(event_params)
      flash[:notice] = 'event was successully updated'
      redirect_to :action => :show, :id => @event.id
    else
      flash[:alert] = 'Event update fail'
      render :action => :edit
    end
  end

  def show
    @event_title = @event.name
  end

  private
    def event_params
      params.require(:event).premit(:name, :description)
    end

    def event_id
      params[:id]
    end
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  def index
  	user ={:id => '1', :name => 'name', :password => 'admin123'}
  	@user = user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def say
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= f.label :name, 'Name' %>
<%= f.text_file, :name %>

<%= f.label :description, 'Discription' %>
<%= f.text_area :description %>

app/views/events/edit.html.erb
<%= form_for @event, :url => {:controller => 'events', :action => 'update'} do |f| %>
  <%= render :particle => 'form', :locals => {:f => f} %>
  <%= f.submit 'Update' %>
<% end %>

app/views/events/index.html.erb
<ul>
  <% @events.each do |event|%>
    <li>
      <%= evnet.name %>
      <%= link_to 'Show', :controller => 'events', :action => 'show', :id => event %>
      <%= link_to 'Edit', :controller => 'events', :action => 'edit', :id => event %>
      <%= link_to 'Delete', :controller => 'events', :action => 'destory', :id => event %>
    </li>
  <% end%>
</ul>
<%= link_to 'New Event', :controller => 'events', :action => 'new' %>

app/views/events/show.html.erb
<%= @event.name %>
<%= simple_format(@event.description)%>
<p> <%= link_to 'Back to index', :controller => 'events', :action => 'index' %> </p>

app/views/home/index.html.erb
<!DOCTYPE html>
<html id="extr-page">
  <head>
    <%= 111 %>
  </head>

  <body class="animated fadeInDown">
    <header id="header">
      <span id="extr-page-header-space">
      <%= yield  %>
      </span>
    </header>

    <div id="main" role="main">
      <!-- ap_main_content -->
      <div id="content" class="container">

        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-5 col-lg-4 col-md-offset-4">
            <div class="text-center">
              <h1>Cirrus / <%= 1234 %></h1>
            </div>

            <div class="well no-padding">
              <%= yield %>
              <!--%= debug(params) if Rails.env.development? %-->
            </div>
                <%= form_for :send,:remote => true, :url =>{:action => :send_email, :controller=>"client"} do |f| %>
			        <div class="form-actions">
			          <div class="row">
			            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			              <%= submit_tag "发送邮件", :id => "button_find", :class => "btn btn-primary"  %>
			            </div>
			          </div>
			        </div>
			    <% end %>
          </div>
        </div>

      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= @event_title || 'Event application' %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  Welcome to user index !
</body>
</html>

app/views/welcome/say.html.erb
<%= Time.now %>
<%= link_to 'Hello', welcome_path%>